spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fh_1811?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: shop-brand-producer

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2





